/**
 * @file main.c
 * @brief Main application entry point
 * 
 * This file contains the main application entry point and initialization
 * sequence. It orchestrates the initialization of all system components
 * and runs the main application loop.
 *
 * Initialization sequence:
 * HAL init
 * Board init (clocks, GPIO)
 * Driver init (I2C2, I2C1, TIM2, DAC1)
 * App init (sensor sampling)
 * Start timer and sensor sampling
 * TIM2 interrupt handler (TIM2_IRQHandler)
 * HAL callback (HAL_TIM_PeriodElapsedCallback) to trigger sensor sampling
 */

#include "main.h"
#include "board_init.h"
#include "board_config.h"
#include "hal_config.h"

/* Application includes */
#include "app.h"
#include "sensor_sampling.h"

/* Driver includes */
#include "ms58.h"
#include "i2c_slave.h"
#include "dac.h"

/* STM32 HAL includes */
#include "stm32l0xx_hal.h"

/* ============================================================================
 * GLOBAL VARIABLES
 * ============================================================================ */

/* HAL peripheral handles - these should be initialized by HAL config */
I2C_HandleTypeDef hi2c1;  /* I2C1 for I2C slave */
I2C_HandleTypeDef hi2c2;  /* I2C2 for pressure sensor */
DAC_HandleTypeDef hdac1;  /* DAC1 for analog outputs */
TIM_HandleTypeDef htim2;  /* TIM2 for 2ms sampling timer */

/* ============================================================================
 * PRIVATE FUNCTIONS
 * ============================================================================ */

/**
 * @brief Initialize HAL peripherals
 * 
 * This function initializes all HAL peripheral handles. The actual
 * configuration should be done in hal_config.c or similar.
 */
static void main_init_hal(void)
{
    /* HAL initialization is typically done via HAL_Init() which:
     * - Configures Flash prefetch, Instruction cache, Data cache
     * - Sets up SysTick for HAL_Delay()
     * - Configures NVIC priority grouping
     */
    HAL_Init();
    
    /* Note: Individual peripheral initialization (I2C, DAC, TIM)
     * should be done in hal_config.c or here if needed */
}

/**
 * @brief Initialize all drivers
 * 
 * Initializes all peripheral drivers with their respective configurations.
 */
static bool main_init_drivers(void)
{
    /* Initialize I2C2 for pressure sensor */
    if (!hal_i2c2_init()) {
        return false;
    }
    
    /* Initialize I2C1 for I2C slave */
    if (!hal_i2c1_init()) {
        return false;
    }
    
    /* Initialize TIM2 for sensor sampling */
    if (!hal_tim2_init()) {
        return false;
    }
    
    /* Initialize DAC1 */
    if (!hal_dac1_init()) {
        return false;
    }
    
    /* TODO: Initialize I2C slave driver */
    /* i2c_slave_init(&hi2c1, BOARD_I2C1_SLAVE_ADDR); */
    
    /* TODO: Initialize DAC driver */
    /* dac_init(&hdac1); */
    
    return true;
}

/**
 * @brief Initialize application logic
 * 
 * Initializes the application layer components.
 */
static bool main_init_app(void)
{
    /* Initialize application layer */
    if (!app_init()) {
        return false;
    }
    
    /* Start sensor sampling */
    if (!sensor_sampling_start()) {
        return false;
    }
    
    /* Start timer to trigger sensor sampling interrupts */
    if (!hal_tim2_start()) {
        return false;
    }
    
    return true;
}

/* ============================================================================
 * PUBLIC FUNCTIONS
 * ============================================================================ */

void main_error_handler(uint32_t error_code)
{
    /* Error handling implementation */
    /* For now, enter infinite loop */
    (void)error_code;
    
    while (1) {
        /* Error state - could blink LED, send error message, etc. */
        HAL_Delay(1000);
    }
}

int main(void)
{
    /* ========================================================================
     * INITIALIZATION SEQUENCE
     * ======================================================================== */
    
    /* 1. Initialize HAL */
    main_init_hal(); // Either to be autogenerated or completely removed 
    
    /* 2. Initialize board hardware (clocks, GPIO) */
    if (!board_init()) {
        main_error_handler(1);
    }
    
    /* 3. Initialize HAL peripherals (I2C, DAC, TIM configurations) */
    /* Note: HAL MSP callbacks in hal_config.c handle GPIO configuration */
    
    /* 4. Initialize drivers */
    if (!main_init_drivers()) {
        main_error_handler(2);
    }
    
    /* 5. Initialize application */
    if (!main_init_app()) {
        main_error_handler(3);
    }
    
    /* ========================================================================
     * MAIN APPLICATION LOOP
     * ======================================================================== */
    
    while (1) {
        /* Main application loop - application logic runs here */
        /* The actual work is done in interrupt handlers and 
         * application callbacks */
        
        /* Call application main loop function */
        app_main_loop();
        
        /* Enter low-power mode if no work to do */
        HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
    }
    
    /* Should never reach here */
    return 0;
}

/* ============================================================================
 * INTERRUPT HANDLERS
 * ============================================================================ */

/**
 * @brief TIM2 interrupt handler
 * 
 * This interrupt is triggered every 2ms to sample the pressure sensor.
 * The actual sensor reading is handled by the sensor_sampling module
 * using a state machine.
 */
void TIM2_IRQHandler(void)
{
    HAL_TIM_IRQHandler(&htim2);
}

/**
 * @brief TIM2 period elapsed callback
 * 
 * Called by HAL when TIM2 period elapses (every 2ms).
 * This triggers the sensor sampling state machine.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == BOARD_TIM2_PERIPH) {
        sensor_sampling_timer_isr();
    }
}
